config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  resources :favorites, only: [:index, :create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:show, :new, :create, :edit, :update]

  resources :posts do
    collection do
      post :confirm
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, presence: true
  validates :image, presence: true

  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  belongs_to :user
  
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, presence: true
    validates :email, presence: true, uniqueness: true
    validates :password, presence: true
    validates :image, presence: true
    
    has_many :posts
    has_many :favorites, dependent: :destroy
    has_many :favorite_posts, through: :favorites, source: :post

    has_secure_password
    mount_uploader :image, ImageUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  before_action :login_required

  private

  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def index
    @user = current_user
    favorites = Favorite.where(user_id: current_user.id).pluck(:post_id)  # ログイン中のユーザーのお気に入りのpost_idカラムを取得
    @favorite_list = Post.find(favorites) 
  end

  def create
    favorite = current_user.favorites.create(post_id: params[:post_id])
    redirect_to posts_path, notice: "#{favorite.post.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to posts_path, notice: "#{favorite.post.user.name}さんのブログをお気に入り解除しました"
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:update, :destroy]
  skip_before_action :login_required, only: [:index, :show]

  def index
    @posts = Post.all
  end

  def new
    if params[:back]
      @post = Post.new(post_params)
    else
      @post = Post.new
    end
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      ContactMailer.contact_mail(@post).deliver
      redirect_to posts_path, notice: "作成しました!!!"
    else
      render :new
    end
  end

  def show
    if logged_in?
      @post = Post.find(params[:id])
      @favorite = current_user.favorites.find_by(post_id: @post.id)
    else
      redirect_to posts_path, notice: "ログインしないと見れないよ？"
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    if @post.update(post_params)
      redirect_to posts_path, notice: "編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url, notice: "削除しました。"
  end

  def confirm
    @post = current_user.posts.new(post_params)
  end

  private
  
  def post_params
    params.require(:post).permit(:content, :image, :image_cache, :user_id)
  end

  def set_post
    @post = current_user.posts.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(email: session_params[:email].downcase)
    if user && user.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to posts_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました!!!'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました!!!'
    redirect_to new_session_path
  end

  private
  def session_params
    params.require(:session).permit(:email, :password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = 'アカウントを作成しました!!!こちらのページからログインして下さい！'
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if current_user == @user
      if @user.update(user_params)
        redirect_to user_path(@user.id), notice: 'アカウント内容を変更しました!!!'
      else
        render :edit
      end
    else
      redirect_to edit_user_path(@user.id), notice: 'パスワードが間違っています!!!'
    end      
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :image_cache)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def choose_new
    if action_name == 'new'
      confirm_posts_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
      current_user.present?
  end
end

app/views/favorites/index.html.erb
<h1>「<%= @user.name %>」のお気に入り一覧</h1>

<% @favorite_list.each do |favotite| %>
  <p>①投稿者:<%= favotite.user.name %></p>
  <p>②内容:<%= favotite.content %></p>
  <p>③画像:<%= favotite.image %></p>
  <br>
<% end %>

<%= link_to '投稿一覧', posts_path, class:"btn btn-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="image">
    <header>
      <hr>
      <% if logged_in? %>
        <h2>「<%= current_user.name %>」でログイン中</h2>
      <% end %>      
      <hr>
    </header>

    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <% if logged_in? %>
      <%= link_to "Profile", user_path(current_user.id), class:"btn btn-success"  %>
      <%= link_to "お気に入り", favorites_path(current_user.id), class:"btn btn-success"  %>
      <%= link_to "ログアウト", session_path(current_user.id), method: :delete, class:"btn btn-success"  %>
    <% else %>
      <%= link_to "新しく作る", new_user_path, class:"btn btn-success" %>
      <%= link_to "ログイン", new_session_path, class:"btn btn-success" %>
      <%= link_to "All Posts", posts_path, class:"btn btn-success"  %>
    <% end %>

      <%= yield %>

    <footer>    
      <hr>
    </footer>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: @post, local: true, url: choose_new) do |form| %>

  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= @post.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
    <%= form.label :image %>
    <%= image_tag(@post.image.url) if @post.image && @post.image.url %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>
  <div class="actions">
    <%= form.submit "確認する" %>
  </div>
<% end %>
<%= link_to '投稿一覧', posts_path, class:"btn btn-primary" %>

app/views/posts/confirm.html.erb
<h2>確認画面</h2>
<%= form_with(model: @post, url: posts_path, local: true) do |form| %>
  <%= form.hidden_field :content %>
  <%= image_tag(@post.image.url) if @post.image && @post.image.url %>
  <%= form.hidden_field :image_cache %>
  <p>本文:<%= @post.content %></p>
  <%= form.submit "投稿する" %>
<% end %>
<%= form_with(model:@post, url:new_post_path, local:true, method:"get") do |form| %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "戻る", name: "back" %>
<% end %>

app/views/posts/edit.html.erb
  <h2>投稿を編集する</h2>
  <%= render 'form' %>

app/views/posts/index.html.erb
<h1>All Posts</h1>
<table>
  <tr>
    <th>投稿内容</th>
    <th>ユーザー名</th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.content %></td>
    <td><%= post.user.name %></td>

    <% if logged_in? && current_user.id == post.user_id %>
      <td><%= link_to '詳細', post_path(post.id), class:"btn btn-secondary" %></td>
      <td><%= link_to "編集", edit_post_path(post.id), class:"btn btn-secondary" %></td>
      <td><%= link_to '削除', post_path(post.id), class:"btn btn-secondary", method: :delete, data: { confirm: '本当に削除していいですか？' } %></td>
    <% else%>
      <td><%= link_to '詳細', post_path(post.id), class:"btn btn-secondary" %></td>
    <% end %>
    
  </tr>
<% end %>

</table>
<br>
<%= link_to '新しく投稿する', new_post_path, class:"btn btn-primary" %>

app/views/posts/new.html.erb
<h2>投稿を作成する</h2>
<%= render 'form' %>

app/views/posts/show.html.erb
<h1>投稿詳細画面</h1>
<h2>
  内容：<%= @post.content %>
  <br>
  画像：<%= image_tag @post.image.url %>
</h2>

<% unless @post.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(post_id: @post.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>

<%= link_to '投稿一覧', posts_path, class:"btn btn-primary" %>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>  
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <br>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <br>
  <%= f.label :image %>
  <%= f.file_field :image %>
  <br>
  <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<h1>アカウント修正</h1>

<%= render 'form' %>

app/views/users/new.html.erb
<h1>アカウント作成</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1>「<%= @user.name %>」のページ</h1>
<p>名前: <%= @user.name %></p>
<p>メールアドレス: <%= @user.email %></p>
<p>登録画像: <%= image_tag @user.image.url %></p>

<%= link_to '投稿一覧', posts_path, class:"btn btn-primary" %>
<%= link_to 'アカウント編集', edit_user_path, class:"btn btn-primary" %>